#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=head;size=1", "id=feet;size=1", "id=hands;size=1", "id=curio;drop_rule=ALWAYS_KEEP"]

