
["General Configs"]

	["General Configs"."Living Bomb"]
		"Should the living bomb effect break blocks?" = false

	["General Configs"."Wild Magic"]
		#Range: 2 ~ 300
		"How many seconds should be waited, till Wild Magic could be applied again?" = 5
		#Range: 0 ~ 100
		"How likely is a wild magic effect if the target is part of the Wild Faction?" = 10
		#Range: 0 ~ 100
		"How likely is a wild magic effect when the target has a Wild Magic Potion Effect?" = 50

	["General Configs"."Glittering Potato"]
		#Range: 1 ~ 20
		"How many HP should be healed with the Glittering Potato?" = 4
		#Range: 0 ~ 99
		"How likely is it for the Glittering Potato to explode?" = 20

	["General Configs".BloodLustBracelet]
		#Range: 1 ~ 100
		"How long is the regeneration effect of the Blood Lust Bracelet? " = 10

	["General Configs".Smite]
		#Range: 1 ~ 100
		"What is the maximum amount of Damage Smites can do in total (Smite Stacking included)" = 10
		#Range: 5 ~ 300
		"Duration of Smite Effects (in s)" = 30
		#Determines the factor by which Dispelling Smite's magnitude is increased when determining whether a mob effect can be removed.
		#Duration (in s) * Amplifier <= Spell-Magnitude * this Factor
		#If the equation is true, the effect can be removed
		#Range: 5 ~ 300
		"Dispelling Smite Mod" = 30

