
["Philip's Ruins"]
	#Tell the game if to use configs for the ruins.
	#By default it is disable, you need to enable it. Make sure you restart the game after editing.
	#Please note that if you use this config file it will override the default spawn weights.
	#Settings apply for most structures. 
	"Enable Configs" = false
	#The structure spawn Separation. The larger the value less of the structure will spawn. Max is 100
	"Structure Separation" = 10
	#Controls the density.
	#The larger the value the more structures will spawn.
	#(Must be less than separation)
	"Structure Density" = 9
	#Seed for structures.
	"Structure Spawn Seed" = 1
	#Set true to disable ruins.
	#This will disable the following
	#structure philipsruins:ancient_ruins
	#structure philipsruins:ancient_crypt
	#structure philipsruins:level_one_ruins
	#structure philipsruins:level_two_ruins
	#structure philipsruins:level_three_ruins
	#structure philipsruins:desert_structures
	#structure philipsruins:badlands_start_dungeon
	#structure philipsruins:badlands_structures
	#structure philipsruins:field_stone_ruins
	#structure philipsruins:field_stone_ruins_rocks
	#structure philipsruins:level_two_ruins_pool
	#structure philipsruins:pumpkin_ruins
	AncientLandRuins = false
	#Set true to disable ruins.
	#This will disable the following
	#structure philipsruins:ocean_fortress
	#structure philipsruins:ocean_ruins
	OceanRuins = false
	#Set true to disable ruins.
	#This will disable the following
	#structure philipsruins:lost_soul_city
	#structure philipsruins:lost_soul_dungeon
	#structure philipsruins:underground_structures
	UndergroundRuins = false

