
["Configs for Plushie Buddies Mod"]
	#How many emeralds do plushies cost
	#Range: 1 ~ 128
	"Emerald count" = 10
	#What trader level sells plushies
	#Range: 1 ~ 5
	"Trader level" = 5
	#'true' or 'false' for plushies being sold by traders
	"If enableded" = true

