
[transceiver]
	maxFMDistance = 350
	falloffFM = 300
	maxAMDistance = 550
	falloffAM = 500

[transmitter]
	maxFMDistance = 1100
	falloffFM = 1000
	maxAMDistance = 2200
	falloffAM = 2000

[radio]
	range = 24

[frequency]
	wholePlaces = 3
	decimalPlaces = 2
	defaultFrequency = "auto-generate"
	crossDimensional = false
	dimensionalInterference = 10
	packetBuffer = 2

