
#General settings
[general]
	#The distance used to spread players in blocks (default: 2000)
	#Range: > 2000
	spreadDistance = 2000

#Blacklist Settings
[blacklist]
	#If this is set to true, the mod will use the tag for ocean biomes to blacklist them (default: true)
	blacklistOceans = true
	#Biomes in this list will be blacklisted from having players spawn in them. By default the mod uses a tag for ocean biomes.
	biomeBlacklist = []

